version: "3.9"

services:

  backend:
    build: ./
    ports:
      - "80:80"
      
  # frontend:
  #   build: ./generateQuote-Frontend
  #   environment:
  #     URL_BACKEND: "localhost:8080"
  #   links:
  #     - "backend"
  #   ports:
  #     - "3000:3000"
    